### ISSUE TITLE
Add directory structure to downloaded files

### ISSUE THREAD

**Issue by huang-jy** [thebigmunch/gmusicapi-scripts#23]
At the moment, the script downloads to the current directory and loose (i.e. no directory structure). Consider adding an option (even if via a switch), to gmdownload and gmsync to create directory structure to put the downloaded files, and optionally breakdown directories in a similar way to how Google's MusicManager (or MusicBrainz' Picard) does. For example:

\
-| Artist 1
--| Album 1
---\ Track xx
--| Album 2
---\ Track xx
-| Artist 2
--| Album 3
---\ Track xx

Also, this would mean changing the way the gmsync works so that it picks up the tracks within the subdirectories. At the moment, I download the tracks, then use Picard to reorganise, but since I have duplicate track names, I lose tracks during the download.

**Comment by thebigmunch** [comment]
This is already possible using the output template system unless I'm missing something. You can specify any base path you want and set up any directory structure you want using the [pattern replacements](https://github.com/thebigmunch/gmusicapi-scripts/wiki/Usage#output-pattern-replacements) that are built in. Check out the [usage documentation](https://github.com/thebigmunch/gmusicapi-scripts/wiki/Usage) for more info.

Also, gmsync should already work recursively detecting local songs.

**Comment by huang-jy** [comment]
The directory structure option mostly works. When trying to use %artist% or
%albumartist% in the form:

gmsync.py down "./%albumartist%/%album%/%track2% - %title%

I get the following:

%albumartist%/[albumname]/[trackno] - [tracktitle]

So it mostly works, but not quite. But, if I take the downloaded track and
feed it into Picard, it then saves it in the correct structure.

And yes, this is a legit purchased album off Gmusic.

**Comment by thebigmunch** [comment]
I'm not sure what you mean by "mostly works". It saves it to the correct paths with the correct metadata from your Google Music library according to you, so I don't see what the problem is or what functionality you're asking to be added.

**Comment by huang-jy** [comment]
Okay, I will have to make do.

**Comment by thebigmunch** [comment]
I don't understand. Your first post asks for functionality that already exists. Your second post shows an example that works correctly that you claim doesn't. What is it that you want?

**Comment by huang-jy** [comment]
The first post asks for functionality, which you pointed out does exist. I
accept that. The second post shows that even when using the examples on the
usage page, the directory structure that is creates does not create the
directory for the artist correctly (i.e. it creates a directory literally
called "%artist%" or "%albumartist%" depending on which of the two I choose
to use) - I don't believe this is correct behaviour?

**Comment by thebigmunch** [comment]
That was not made clear in your post. That will happen when there's no data in those metadata fields for those tracks; this is the expected and my desired behavior. I'd imagine Picard is grabbing information from MusicBrainz to fill in missing metadata, which is outside the scope of my scripts; they can only work with the metadata that exists within the local files and Google Music song entries.

**Comment by huang-jy** [comment]
I see. In that case, I'll just rename it after the script finishes. Thanks
for your time.
