### ISSUE TITLE
Port to new standalone wrapper (testers wanted)

### ISSUE THREAD

**Issue by thebigmunch** [thebigmunch/gmusicapi-scripts#26]
I have finally released a completely standalone [wrapper interface](https://github.com/thebigmunch/gmusicapi-wrapper). The devel branch has the package ported to use this new wrapper interface. Also, it's now installable (preferred), but I've left some redirect scripts to allow for backward compatibility with repo cloning.

I could use some help from users willing to test this new version to make sure I haven't missed anything that broke. Should be as simple as checking out and pulling the dev branch if you don't want to install it. If you'd like to install it, first install the devel branch of [gmusicapi-wrapper](https://github.com/thebigmunch/gmusicapi-wrapper#installation) and then run ``pip install git+https://github.com/thebigmunch/gmusicapi-scripts@devel``.

**Comment by Crono141** [comment]
Hey.  Downloaded the devel branch and installed them yesterday to try and fix the issue I reported last weekend.  The issue I ran into is that the gmsync script doesn't recurs into subfolders like it should.  It recognized and uploaded the one song I had at the root music folder level, but did not recurs into any of the subdirectories.

I attempted to manually set a max-depth of 0, but this did not improve the situation.  Anything you'd like me to try manually to get to the root of the problem?

**Comment by thebigmunch** [comment]
Yup. Forgot I had pushed the max-depth stuff to the devel branches on GitHub. Logic error introduced by me when I changed the behavior of the default max-depth setting from being equivalent to max-depth of 1 to being infinite recursion. Go ahead do an upgrade install of gmusicapi-wrapper from its devel branch. Should fix it.

**Comment by Crono141** [comment]
That got the process started.  Thanks.  Looks like the compare isn't quite correct though.

>Loaded 1621 Google Music songs        
>                       
>Loading local songs...     
>/mnt/raid/public/Music/Sonata Arctica/Unia/01 In Black and White.mp3 is not a valid music file!                                                       
>Excluded 0 local songs.                                       
>Filtered 1 local songs.                                          
>Loaded 16734 local songs.                        
>                                                                           
>Scanning for missing songs...                               
>                                                               
>Uploading 14650 song(s) to Google Music 
>                                                                            
>(    1/14650) Failed to upload -- /mnt/raid/public/Music/AmBeam/AmBeam - poligon.ogg | ALREADY >EXISTS
>

The total number of songs in the library minus the total number of songs already on google should add up to the total number to upload or more (since some songs are bought on google, and thus not part of the local library).  But I have less here (16734-1621=15113 vs 14650).  Also, the very first song it uploaded already existed, so that's another indicator that something is awry.  So far though thats been the only duplicate, so perhaps it has something to do with that file in particular.

But thanks to your update i'm able to get most of the library uploaded.  I appreciate the quick responses.

**Comment by thebigmunch** [comment]
Missing metadata values or metadata differences from one end or the other are the most common cause. For example, if something is tagged with an album on local but not on Google Music, that would be flagged for upload but would then match the acoustic id when upload is attempted. There may potentially be some super rare cases which aren't covered, but I haven't really gotten reports of anything being missed by the [normalization](https://github.com/thebigmunch/gmusicapi-wrapper/blob/devel/gmusicapi_wrapper/utils.py#L49).

Another potential cause could be multiple copies of songs with matching metadata. The fields used for comparison are artist, album, title, and tracknumber. Cases of missing metadata fields may cause a discrepancy as well.

Though it's probably not feasible with that many songs, if you do find that the cause is somewhere within my scripts or wrapper, please let me know. But you could check that first song that already exists specifically to see any mismatching of metadata is the cause for that case.
