### ISSUE TITLE
InsecureRequestWarning complaint by python urllib

### ISSUE THREAD

**Issue by BenoitDuffez** [thebigmunch/gmusicapi-scripts#28]
I've got warnings when using the `gmsync.py` script:

    /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py:769: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
    InsecureRequestWarning)

I'm guessing some of the HTTPS connection made to google music encounter some bogus certificates. I doubt that Google would use HTTPS without a valid certificate.

I'm far from knowing python so unfortunately I can't really fix the issue myself. Has it been reported already? is it valid?

**Comment by thebigmunch** [comment]
It's not that they're invalid certs. It's that Google uses self-signed certs in places.

See https://github.com/simon-weber/Unofficial-Google-Music-API/issues/313 and https://github.com/kennethreitz/requests/issues/2214. Basically, you'll keep getting them until the behavior is changed in requests.

**Comment by BenoitDuffez** [comment]
I didn't expect this from google. Thanks for the quick reply!
Cheers

**Comment by thebigmunch** [comment]
Might as well leave this open until it's resolved upstream so it's easier for anyone else to see.

**Comment by thebigmunch** [comment]
gmusicapi put a workaround in place for this, so shouldn't be an issue anymore.
