### ISSUE TITLE
Skip already uploaded tracks 

### ISSUE THREAD

**Issue by quasar** [thebigmunch/gmusicapi-scripts#30]
Hello and thank you for your script!

Is there any way to skip already uploaded tracks? It is useful when reuploading a large directory with lots of files.

Something like hashes comparing or something.

**Comment by stephenjamieson** [comment]
look at the gmsync script?

**Comment by quasar** [comment]
Oh, I thought it would donwload from GM missing tracks locally

**Comment by stephenjamieson** [comment]
```
Commands:
  up                             Sync local songs to Google Music. Default behavior.
  down                           Sync Google Music songs to local computer.
```

**Comment by quasar** [comment]
Thank you for your help.

**Comment by thebigmunch** [comment]
Also, running it without a command will upload for backward compatibility with older versions which only did uploading.
