### ISSUE TITLE
Search fails for tracks without track number

### ISSUE THREAD

**Issue by ryankaiser** [thebigmunch/gmusicapi-scripts#40]
Tracks which don't have a track number in their metadata produce errors with search script when attempting to sort by "trackNumber". The script should either check for the existence of track numbers before sorting, or include a command line switch to sort by something else.

**Comment by thebigmunch** [comment]
You didn't post the errors you get, song dict of nonworking examples, nor I can't replicate this behavior in the interpreter, at least. Will test with the script itself when I get around to it, but I don't see how it would be different than just doing ``mc.get_all_songs().sort(key=lambda song: (song.get('artist'), song.get('album'), song.get('trackNumber')))`` in the interpreter if the errors you're getting are actually related to the sorting.

**Comment by thebigmunch** [comment]
Closing this due to lack of response or reproduction.
