### ISSUE TITLE
Add %suggested% template pattern to output option when value is directory

### ISSUE THREAD

**Issue by rombert** [thebigmunch/gmusicapi-scripts#41]
I briefly skimmed the docs for the scripts and decided that './gmdownload.py /some/path/to/Music/` was what I wanted. Obviously ( in retrospect ) it downloaded everything to a file named '.mp3' in the directory I specified.

I think there should be a better response to this, any of 

- stop the download and ask the user to specify a valid template
- append the default template and use the directory as a download base

**Comment by thebigmunch** [comment]
This was a change I have locally. I just haven't had time to get things chugging along again on my hobby code projects until recently.
