### ISSUE TITLE
Music Upload does not properly match existing songs before upload starts

### ISSUE THREAD

**Issue by Crono141** [thebigmunch/gmusicapi-scripts#45]
When uploading my music library, the gmupload.py script does not properly check the local library against the existing google library.  No songs are excluded. Upload then attempts to upload each song, which produces an error on each existing song.  This takes approx 1 sec per song.  While this might result in being functional, it would take approx 4.5 hours to check through a google library of 16,000 songs.
Output below:

>master@HomeServer:~/gmusicapi-scripts$ ./gmupload.py -m "/mnt/raid/public/Music"
>Successfully logged in.
>
>Loading local songs...
>Excluded 0 local songs.
>Filtered 0 local songs.
>Loaded 16735 local songs.
>
>Uploading 16735 songs to Google Music
>
>(    1/16735) Failed to upload  /mnt/raid/public/Music/08_Through_The_Precious_Blood.m4a | >ALREADY EXISTS
>(    2/16735) Failed to upload  /mnt/raid/public/Music/10_Come_Thou_Fount.m4a | ALREADY >EXISTS
>(    3/16735) Failed to upload  /mnt/raid/public/Music/311/311- Love Song.mp3 | ALREADY EXISTS
>Uploading  /mnt/raid/public/Music/634 Project and Toshiro Masuda/NARUTO The Movi^C- >Daikatsugeki! Yukihime Ninpocho Dattebayo!! OST/01 Konoha Densetsu.mp3
>
>Exiting

Would it be possible to query the list of files on googles end first, and then compare it against the target folders specified to upload, and generate a filter at runtime?  This would prevent iterating through an entire library and attempting to upload before discovering the file already exists.

**Comment by Crono141** [comment]
Nevermind.  gmsync is the command that has this behavior, not upload.  Perhaps documentation could be updated to make this distinction a little more clear.

**Comment by Crono141** [comment]
However, now that I'm trying to use gmsync, I'm getting a python error.

Loading Google Music songs...
Filtered 0 Google Music songs
Loaded 1620 Google Music songs

Loading local songs...
Excluded 0 local songs.
Filtered 0 local songs.
Loaded 16735 local songs.

Scanning for missing songs...
Traceback (most recent call last):
  File "./gmsync.py", line 202, in <module>
    main()
  File "./gmsync.py", line 164, in main
    upload_songs = compare_song_collections(local_songs, google_songs)
  File "/home/master/gmusicapi-scripts/gmwrapper.py", line 49, in compare_song_collections
    src_key = create_song_key(src_song)
  File "/home/master/gmusicapi-scripts/gmwrapper.py", line 68, in create_song_key
    song = song if isinstance(song, dict) else _mutagen_fields_to_single_value(song)
  File "/home/master/gmusicapi-scripts/gmwrapper.py", line 35, in _mutagen_fields_to_single_value
    return {k: v[0] for k, v in mutagen.File(file, easy=True).iteritems()}
  File "/usr/local/lib/python2.7/dist-packages/mutagen/_file.py", line 251, in File
    return Kind(filename)
  File "/usr/local/lib/python2.7/dist-packages/mutagen/_file.py", line 42, in __init__
    self.load(filename, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mutagen/id3/__init__.py", line 1093, in load
    self.info = self._Info(fileobj, offset)
  File "/usr/local/lib/python2.7/dist-packages/mutagen/mp3.py", line 185, in __init__
    self.__try(fileobj, offset, size - offset, False)
  File "/usr/local/lib/python2.7/dist-packages/mutagen/mp3.py", line 223, in __try
    raise HeaderNotFoundError("can't sync to an MPEG frame")
mutagen.mp3.HeaderNotFoundError: can't sync to an MPEG frame

**Comment by thebigmunch** [comment]
The devel branch that uses my standalone wrapper (also devel branch) covers this. I will finally get around to releasing it officially this weekend. It's hitting an mp3 file that is an invalid or corrupt mp3 file.
