### ISSUE TITLE
Failed to upload .. ALREADY_EXISTS

### ISSUE THREAD

**Issue by smoser** [thebigmunch/gmusicapi-scripts#47]
Hi,
Had used gmusic-sync a while ago, and needed to upload something new.  My old virtual env failed to upload, and I think left in a bad state.  Tried to create a new virtual env and try the devel branches:
  pip install git+https://github.com/thebigmunch/gmusicapi-wrapper.git@devel
  pip install git+https://github.com/thebigmunch/gmusicapi-scripts@devel

Then:
```
$ gmsync up --log mp3/The_Thirsting-Companions_of_the_Lamb/
2015-11-23 21:37:11,052 - gmusicapi.Musicmanager1 (musicmanager:510) [WARNING]: upload of 'mp3/The_Thirsting-Companions_of_the_Lamb/11-I_have_Fought_the_Good_Fight.mp3' rejected: TrackSampleResponse code 4: ALREADY_EXISTS(c61a83a5-0341-3a90-9b4f-20b6942b3c5b)
(11/11) Failed to upload -- mp3/The_Thirsting-Companions_of_the_Lamb/11-I_have_Fought_the_Good_Fight.mp3 | ALREADY EXISTS
```

But searching shows:
```
$ gmsearch -f "artist:.*hirsting.*"
Successfully logged in.
Scanning for songs...
Loading Google Music songs...
Filtered ... Google Music songs
Loaded 0 Google Music songs
No songs found matching query
All done!
```

Logging into the web view also does not show any albums for anything i can manage to search for.
I can provide more info if needed. 

Also, interestingly searching prompts for user / password, but upload does not (as I have logged in before)

**Comment by thebigmunch** [comment]
This is likely related to #46 where there is a link to the related gmusicapi issue.

Also, it's not interesting that you need to put in your user/password for Mobileclient functionality and not Musicmanager. Musicmanager uses and stores an oauth credential, Mobileclient does not.

**Comment by smoser** [comment]
Thanks for triaging.
Yeah, I didn't mean to say that search prompting for password was related to the bug, but just kind of expected it to use the oauth credential also.
Thanks.

**Comment by thebigmunch** [comment]
This has been fixed in gmusicapi.
