### ISSUE TITLE
Feature: use Musicmanager option for gmsearch

### ISSUE THREAD

**Issue by olemma** [thebigmunch/gmusicapi-scripts#54]
gmsearch uses mobileclient, which doesn't work if you have 2-factor authentication enabled, but the same functionality can be provided by musicmanager and oauth.

**Comment by thebigmunch** [comment]
Music Manager can't get All Access library tracks, so it doesn't provide the same functionality. Also, you can use an app-specific password for the Mobileclient unlike the Webclient.
