### ISSUE TITLE
KeyError when uploading particular files

### ISSUE THREAD

**Issue by jcrevier** [thebigmunch/gmusicapi-scripts#55]
Script seems to run fine until it hits a couple different files, then it gets tripped up and I get the following traceback.
Any idea what might be causing this? 

```
Traceback (most recent call last):
  File "/usr/bin/gmsync", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/gmusicapi_scripts/gmsync.py", line 223, in main
    mmw.upload(songs_to_upload, enable_matching=cli['match'], delete_on_success=cli['delete-on-success'])
  File "<string>", line 2, in upload
  File "/usr/lib/python2.7/site-packages/gmusicapi/utils/utils.py", line 613, in wrapper
    return function(*args, **kw)
  File "/usr/lib/python2.7/site-packages/gmusicapi_wrapper/gmusicapi_wrapper.py", line 542, in upload
    if any(exist_string in not_uploaded[filepath] for exist_string in exist_strings):
  File "/usr/lib/python2.7/site-packages/gmusicapi_wrapper/gmusicapi_wrapper.py", line 542, in <genexpr>
    if any(exist_string in not_uploaded[filepath] for exist_string in exist_strings):
KeyError: u'/mnt/media/music/Music/Andrew Bird/The Mysterious Production of Eggs/06 Banking on a Myth.m4a
```

**Comment by thebigmunch** [comment]
This is due to simon-weber/gmusicapi#412. I'll be submitting a PR that will make gmusicapi's upload method return the matched result even when matching is disabled. Hopefully a bugfix release of gmusicapi will follow.

**Comment by jcrevier** [comment]
Good to know it's identified already then. I closed my issue b/c I hadn't
realized there was a version of the script in Python 3, and I was using a
prior version, but it looks like that is also affected.

**Comment by thebigmunch** [comment]
@jcrevier and everyone else: The PRs to get uploading working properly again were merged today, so next gmusicapi version will fix this. If you don't want to wait until the next release, you can use ``pip install --upgrade git+https://github.com/simon-weber/gmusicapi@develop`` to install from git.
