### ISSUE TITLE
Can't handle certain unicode characters

### ISSUE THREAD

**Issue by kilbyjmichael** [thebigmunch/gmusicapi-scripts#58]
```
Traceback (most recent call last):
  File "/usr/bin/gmdownload", line 9, in <module>
    load_entry_point('gmusicapi-scripts==0.3.0', 'console_scripts', 'gmdownload')()
  File "/usr/lib/python3.5/site-packages/gmusicapi_scripts/gmdownload.py", line 100, in main
    mmw.download(songs_to_download, cli['output'])
  File "<decorator-gen-124>", line 2, in download
  File "/usr/lib/python3.5/site-packages/gmusicapi/utils/utils.py", line 619, in wrapper
    return function(*args, **kw)
  File "/usr/lib/python3.5/site-packages/gmusicapi_wrapper/musicmanager.py", line 229, in download
    for result in self._download(songs, template):
  File "/usr/lib/python3.5/site-packages/gmusicapi_wrapper/musicmanager.py", line 195, in _download
    shutil.move(temp.name, filepath)
  File "/usr/lib/python3.5/shutil.py", line 527, in move
    if os.path.isdir(dst):
  File "/usr/lib/python3.5/genericpath.py", line 42, in isdir
    st = os.stat(s)
UnicodeEncodeError: 'ascii' codec can't encode character '\x8d' in position 8: ordinal not in range(128)

```

**Comment by thebigmunch** [comment]
What encoding is set for your shell?

**Comment by kilbyjmichael** [comment]
Do you mean locales and such? It should all be UTF-8. Is there any more info I can give you on this?

**Comment by thebigmunch** [comment]
Should be or is?

**Comment by kilbyjmichael** [comment]
I have checked on an ubuntu machine and an arch machine both with UTF-8 encoding and it still does not work. Is it something wrong with my enviroment or the script?

**Comment by thebigmunch** [comment]
I have no idea. I haven't run into any trouble downloading any unicode stuff I've thrown at it. From something common stuff like ``í`` to more obscure stuff like ``☆``.

**Comment by kilbyjmichael** [comment]
Alright, well thanks for the info! If I come up with anything more
substantial I'll report it. Thanks for making a cool script!

**Comment by thebigmunch** [comment]
Just so I can test the same thing as you, can you post the character that's causing the problem?

**Comment by kilbyjmichael** [comment]
\x8d

**Comment by thebigmunch** [comment]
No. I need the actual string that it's failing on.

**Comment by kilbyjmichael** [comment]
Is there a way I can get the string that the script fails on? Its pulling from my google music. Is there a way to see what song it fails on?

**Comment by thebigmunch** [comment]
It should be fairly obvious by the progress to see what song it was trying to download at the time. Songs are sorted by artist > album > track_number before downloading.

**Comment by thebigmunch** [comment]
Closing since there hasn't been a response in a month.
