### ISSUE TITLE
gmsearch always ask for user name and password

### ISSUE THREAD

**Issue by pejobo** [thebigmunch/gmusicapi-scripts#59]
as title says (git version)
gmdownload works as expected (not asking for credentials after first login)

**Comment by thebigmunch** [comment]
gmdownload uses the Musicmanager protocol which uses OAuth and saves your credential to disk which is why there is no username/password options for it. gmsearch uses Mobileclient which uses ClientLogin which requires username/password and doesn't save them to disk.

This is expected.

**Comment by thebigmunch** [comment]
Oh, and, if you want to keep tabs on OAuth support for the Mobileclient interface, check out simon-weber/gmusicapi#426

**Comment by pejobo** [comment]
Hm, ok, but why not use the Musicmanager protocol for gmsearch, too? Looks for me like gmdownload does the same search as gmsearch.. at least both use the same set of parameters..

**Comment by thebigmunch** [comment]
The Music Manager API can only get uploaded and purchased songs from your library, not subscription songs.

**Comment by pejobo** [comment]
My use case is that I want to check my query before downloading. I tried "-d" (dry run) with gmdownload (the documentation there talks about "upload"), but this just wrote my whole google song library to standard out. I need a list of songs which would be downloaded..
Should I write a new report to improve this behaviour?

**Comment by thebigmunch** [comment]
The dry run will output what would be filtered, excluded, and downloaded. If it's going to be a lot, you probably want to redirect the output to a file and check it out there.
