### ISSUE TITLE
gmdownload loads songs twice

### ISSUE THREAD

**Issue by pejobo** [thebigmunch/gmusicapi-scripts#60]
As title says. I would recommend adding a check for duplicate song ids before downloading..

```
[xxx@xxx Rekord (2014)]$ LC_ALL=de_DE.UTF-8 gmdownload -a -f 'artist:Fantastischen' -f 'album:Rekord'
Successfully logged in to Musicmanager.

Loading Google Music songs...
Filtered 1696 Google Music songs
Loaded 26 Google Music songs

Downloading 26 song(s) from Google Music

( 1/26) Successfully downloaded -- 02 - Heute.mp3 (991a1afb-818c-3576-97ab-220d61bc18dd)
( 2/26) Successfully downloaded -- 02 - Heute.mp3 (991a1afb-818c-3576-97ab-220d61bc18dd)
( 3/26) Successfully downloaded -- 03 - Und Los.mp3 (038a7aa9-2d98-36dc-a82c-14664e73184c)
( 4/26) Successfully downloaded -- 03 - Und Los.mp3 (038a7aa9-2d98-36dc-a82c-14664e73184c)
( 5/26) Successfully downloaded -- 04 - Lass Sehen.mp3 (364e85e3-a50c-332e-bba2-d8201df20323)
( 6/26) Successfully downloaded -- 04 - Lass Sehen.mp3 (364e85e3-a50c-332e-bba2-d8201df20323)
```

**Comment by thebigmunch** [comment]
You may want to check to see if you have duplicate songs on Google Music. You may have run into https://github.com/simon-weber/gmusicapi/issues/397#issuecomment-187832958

**Comment by pejobo** [comment]
If I search on the website there are no duplicates for these songs.
And the music was purchased, not uploaded.

**Comment by thebigmunch** [comment]
Can you see what happens when you use [this](https://unofficial-google-music-api.readthedocs.org/en/latest/reference/musicmanager.html#gmusicapi.clients.Musicmanager.get_uploaded_songs) and [this](https://unofficial-google-music-api.readthedocs.org/en/latest/reference/musicmanager.html#gmusicapi.clients.Musicmanager.get_purchased_songs) directly? I'm wondering if those songs are returned for both. I don't have any purchased music to test with.

**Comment by pejobo** [comment]
I made a simpler test: It only happens with purchased songs.

**Comment by thebigmunch** [comment]
I need you to test if those songs are returned by get_uploaded_songs as well as get_purchased_songs, which would be my first guess as to why there are doubles of those songs.

**Comment by pejobo** [comment]
sorry, get_uploaded_songs from Musicmanager in python console gives me an exception :(

**Comment by thebigmunch** [comment]
What exception?

Alternatively, you can go into gmdownload.py and change the line ``songs_to_download, songs_to_filter = mmw.get_google_songs(include_filters, exclude_filters, cli['all-includes'], cli['all-excludes'])`` to ``songs_to_download, songs_to_filter = mmw.get_google_songs(include_filters, exclude_filters, cli['all-includes'], cli['all-excludes'], purchased=False)``. If the purchased songs still get downloaded but not doubled, then we'll have our answer.

**Comment by pejobo** [comment]
This is the result with your proposed change:
```
[xx@xx]$ gmdownload -a -f 'artist:Fantastischen' -f 'album:Rekord' -f 'title:Heute'
Successfully logged in to Musicmanager.

Loading Google Music songs...
Filtered 1470 Google Music songs
Loaded 1 Google Music songs

Downloading 1 song(s) from Google Music

(1/1) Successfully downloaded -- 02 - Heute.mp3 (991a1afb-818c-3576-97ab-220d61bc18dd)

All done!
```

**Comment by thebigmunch** [comment]
Can you now change ``purchased=False`` to ``uploaded=False`` and post the output?

That last test showed that at least one song was returned when only uploaded songs were requested.

**Comment by pejobo** [comment]
With _uploaded=False_ the output is same.

**Comment by thebigmunch** [comment]
You should be able to ``pip install --upgrade git+https://github.com/thebigmunch/gmusicapi-wrapper@devel`` to install the devel branch which should have this fixed. Check it out and let me know.

**Comment by pejobo** [comment]
Works for me, it just downloads one song with the test command mentioned earlier.
Thanks for your effort.
