### ISSUE TITLE
Using %suggested% with gmsync uses a single file name for multiple downloads

### ISSUE THREAD

**Issue by rombert** [thebigmunch/gmusicapi-scripts#61]
I synced 7 songs today and I got the same name for all 7.

$ ./gmsync down ~/Music/%artist%/%album%/%suggested%

Successfully logged in to Musicmanager.

Loading Google Music songs...
Filtered 0 Google Music songs
Loaded 408 Google Music songs

Loading local songs...
Excluded 0 local songs.
Filtered 0 local songs.
Loaded 279 local songs.

Scanning for missing songs...

Downloading 7 song(s) from Google Music

(1/7) Successfully downloaded -- /home/robert/Music/Foo Fighters/Saint Cecilia EP/01 - Saint Cecilia.mp3 (8f52267b-4fcd-3245-a6af-49e49cef8de5)
(2/7) Successfully downloaded -- /home/robert/Music/Foo Fighters/Saint Cecilia EP/01 - Saint Cecilia.mp3 (af85bbf2-8e00-3cf6-9c23-23b4e52f71a0)
(3/7) Successfully downloaded -- /home/robert/Music/Foo Fighters/Saint Cecilia EP/01 - Saint Cecilia.mp3 (c7850cd1-d960-3e32-8a69-830eef8deaed)
(4/7) Successfully downloaded -- /home/robert/Music/Foo Fighters/Saint Cecilia EP/01 - Saint Cecilia.mp3 (1457c865-c23d-3ef0-b235-37a47f7ef825)
(5/7) Successfully downloaded -- /home/robert/Music/Foo Fighters/Saint Cecilia EP/01 - Saint Cecilia.mp3 (8cef5fb1-a86a-3b26-9b42-3102ca0142b2)
(6/7) Successfully downloaded -- /home/robert/Music/Pantera/Vulgar Display Of Power/01 - Saint Cecilia.mp3 (51ff2ad5-d232-3d95-8b46-e52f77d246b8)
(7/7) Successfully downloaded -- /home/robert/Music/Rage Against The Machine/Rage Against The Machine/01 - Saint Cecilia.mp3 (67af84ff-0377-352e-a4d0-4ee0d86d8689)

**Comment by rombert** [comment]
2 notes:

1. Using %title% does not have the same problem
1. Deleting the whole folder and retrying to sync shows the same issue - it's just that another track ( the first one to be downloaded ) is used for picking the file name

**Comment by thebigmunch** [comment]
Yeah, sorry 'bout that. Been working a lot on gmusicapi itself and been neglecting my own stuff a bit as a result. I'll push a fix for this later today and probably make a release to go along with it. Thanks for bringing it to my attention.

**Comment by thebigmunch** [comment]
PS This is an issue in gmusicapi-wrapper, so that's what you'll need to update, not gmusicapi-scripts.

**Comment by rombert** [comment]
Ack, thanks for the info. I used pip to install, should I use something like ``` pip install gmusicapi-wrapper --upgrade``` once the release is done?

**Comment by thebigmunch** [comment]
You should be able to ``pip install --upgrade git+https://github.com/thebigmunch/gmusicapi-wrapper@devel`` to install the devel branch which should have this fixed. Check it out and let me know.

**Comment by rombert** [comment]
Thanks for the quick turnaround! I tried to upgrade but I received an error - running in a pyenv

**Comment by thebigmunch** [comment]
A permission error seems like a problem on your system. Not much I can do about it.
