### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf3' in position 7: ordinal not in range(128)

### ISSUE THREAD

**Issue by gothink** [thebigmunch/gmusicapi-scripts#62]
When trying to use 'gmsync up' to upload my music folder to Google Music it fails when comparing the tracks.

Successfully logged in to Musicmanager.

Loading Google Music songs...
Filtered 0 Google Music songs
Loaded 12788 Google Music songs

Loading local songs...
Excluded 0 local songs.
Filtered 0 local songs.
Loaded 4836 local songs.

Scanning for missing songs...
Traceback (most recent call last):
  File "/usr/local/bin/gmsync", line 9, in <module>
    load_entry_point('gmusicapi-scripts==0.3.0', 'console_scripts', 'gmsync')()
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi_scripts/gmsync.py", line 167, in main
    songs_to_upload = compare_song_collections(matched_local_songs, matched_google_songs)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi_wrapper/utils.py", line 107, in compare_song_collections
    src_key = _create_song_key(src_song)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi_wrapper/utils.py", line 85, in _create_song_key
    metadata.append(_normalize_metadata(song[field]))
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi_wrapper/utils.py", line 52, in _normalize_metadata
    metadata = str(metadata)  # Convert metadata to unicode.
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf3' in position 7: ordinal not in range(128)

Versions:
`Name: gmusicapi
Version: 10.0.0
Location: /usr/local/lib/python2.7/dist-packages
Requires: validictory, decorator, mutagen, requests, python-dateutil, proboscis, oauth2client, mock, appdirs, gpsoauth, MechanicalSoup, pyopenssl, ndg-httpsclient, pyasn1, six, future, protobuf
`
`Name: gmusicapi-scripts
Version: 0.3.0
Location: /usr/local/lib/python2.7/dist-packages
Requires: gmusicapi-wrapper, docopt-unicode
`

This seems somewhat similar to a few other issues I've seen here and on the https://github.com/simon-weber/gmusicapi issues page:
https://github.com/thebigmunch/gmusicapi-scripts/issues/58
https://github.com/thebigmunch/gmusicapi-scripts/issues/52
https://github.com/simon-weber/gmusicapi/issues/394

Any help would be appreciated. I haven't been able to get this working (first time testing it out). Please let me know if there's any other info you need.

**Comment by thebigmunch** [comment]
You seem to have them installed with Python 2.7. gmusicapi-scripts hasn't supported Python 2 in a few months, and installation should have failed with a message saying as such on any Python version less than 3.4.

**Comment by gothink** [comment]
How silly of me. It might be possible I installed this a while back without using it and just upgraded to the latest version (I honestly can't recall).

Anyway, I've completed removed the version installed with 2.7 and reinstalled with 3.4. Everything is working now. Thanks for the help!
