### ISSUE TITLE
Unable to upload embedded album cover

### ISSUE THREAD

**Issue by hellohuan** [thebigmunch/gmusicapi-scripts#67]
**Please read the contributing guidelines linked above before opening an issue.**
As stated in the title, the script can't upload the embedded album art. 

![screenshot 2016-08-02 22-51-38](https://cloud.githubusercontent.com/assets/3334833/17333170/e935e1ba-5903-11e6-964f-e21962a65119.png)

The format of the song is .m4a, as shown in the screenshot. The song has an embedded album cover(left), after being uploaded with the script, the cover is gone(right). I've tried other format like .mp3 file, and same problem exists.

**Comment by thebigmunch** [comment]
There is an issue about album art here already and one on the repo for gmusicapi itself. Internal art uploading would definitely be added to gmusicapi. External art uploading may be added to gmusicapi or be added to my wrapper used by these scripts.
